POST http://localhost:8080/account HTTP/2
content-type: application/json

{
  "first_name" : "Tin",
  "last_name" : "Panuraksirikul",
  "email" : "tin123@gmail.com",
  "id_card_no" : "1100123254775",
  "date_of_birth" : "2002-9-15"
}